<?php
/**
 * CustomerSessionSubIdsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * production-lychee-api-v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-11-07T20:47:19Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerSessionSubIdsTest Class Doc Comment
 *
 * @category    Class */
// * @description CustomerSessionSubIds
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerSessionSubIdsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerSessionSubIds"
     */
    public function testCustomerSessionSubIds()
    {
    }

    /**
     * Test attribute "subId"
     */
    public function testPropertySubId()
    {
    }

    /**
     * Test attribute "subId2"
     */
    public function testPropertySubId2()
    {
    }

    /**
     * Test attribute "subId3"
     */
    public function testPropertySubId3()
    {
    }

    /**
     * Test attribute "clickId"
     */
    public function testPropertyClickId()
    {
    }
}
