<?php
/**
 * CustomerSessionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * production-lychee-api-v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-11-03T17:09:03Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerSessionTest Class Doc Comment
 *
 * @category    Class */
// * @description CustomerSession
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerSessionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CustomerSession"
     */
    public function testCustomerSession()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "sessionId"
     */
    public function testPropertySessionId()
    {

    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

    /**
     * Test attribute "expiredAt"
     */
    public function testPropertyExpiredAt()
    {

    }

    /**
     * Test attribute "merchantId"
     */
    public function testPropertyMerchantId()
    {

    }

    /**
     * Test attribute "partnerId"
     */
    public function testPropertyPartnerId()
    {

    }

    /**
     * Test attribute "affiliateInfoId"
     */
    public function testPropertyAffiliateInfoId()
    {

    }

    /**
     * Test attribute "productId"
     */
    public function testPropertyProductId()
    {

    }

    /**
     * Test attribute "destinationId"
     */
    public function testPropertyDestinationId()
    {

    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {

    }

}
