<?php
/**
 * CustomerSessionServerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * production-lychee-api-v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-11-07T03:14:22Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerSessionServerTest Class Doc Comment
 *
 * @category    Class */
// * @description CustomerSessionServer
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerSessionServerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CustomerSessionServer"
     */
    public function testCustomerSessionServer()
    {

    }

    /**
     * Test attribute "hTTPUSERAGENT"
     */
    public function testPropertyHTTPUSERAGENT()
    {

    }

    /**
     * Test attribute "hTTPREFERER"
     */
    public function testPropertyHTTPREFERER()
    {

    }

    /**
     * Test attribute "hTTPACCEPTLANGUAGE"
     */
    public function testPropertyHTTPACCEPTLANGUAGE()
    {

    }

    /**
     * Test attribute "qUERYSTRING"
     */
    public function testPropertyQUERYSTRING()
    {

    }

}
